
export const PLAYER_HEALTH = 4;
export const PLAYER_LIVES = 3;
export const PLAYER_SCORE = 100;
export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_LIFESPAN = 3;
export const PLAYER_BULLET_MAX_COUNT = 10;

export const ENEMY_SCOUT_HEALTH = 2;
export const ENEMY_SCOUT_SCORE = 150;
export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 2;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 2;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 40;

export const ENEMY_SCOUT_GROUP_SPAWN_START = 1000;
export const ENEMY_SCOUT_GROUP_SPAWN_INTERVAL = 5000;


export const ENEMY_FIGHTER_HEALTH = 2;
export const ENEMY_FIGHTER_SCORE = 200;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 3;
export const ENEMY_FIGHTER_BULLET_SPEED = -140; //needs to be negative to go down or you can multiply by flipY
export const ENEMY_FIGHTER_BULLET_INTERVAL = 6000;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 10;

export const ENEMY_FIGHTER_GROUP_SPAWN_START = 3000;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 9000;

export const ENEMY_BOMBER_HEALTH = 1;
export const ENEMY_BOMBER_SCORE = 250;
export const ENEMY_BOMBER_MOVEMENT_VERTICAL_VELOCITY = 1;
export const ENEMY_BOMBER_BULLET_SPEED = -100;
export const ENEMY_BOMBER_BULLET_INTERVAL = 4500;
export const ENEMY_BOMBER_BULLET_LIFESPAN = 3;
export const ENEMY_BOMBER_BULLET_MAX_COUNT = 10;

// export const ENEMY_BOMBER_GROUP_SPAWN_START = 3000;
// export const ENEMY_BOMBER_GROUP_SPAWN_INTERVAL = 6000;



export const ENEMY_AIRCRAFT_CAREER_HEALTH = 16;
export const ENEMY_AIRCRAFT_CAREER_SCORE = 400;
export const ENEMY_AIRCRAFT_CAREER_MOVEMENT_VERTICAL_VELOCITY = 1;
export const ENEMY_AIRCRAFT_CAREER_BULLET_SPEED = -150; //needs to be negative to go down or you can multiply by flipY
export const ENEMY_AIRCRAFT_CAREER_BULLET_INTERVAL = 4000;
export const ENEMY_AIRCRAFT_CAREER_BULLET_LIFESPAN = 5;
export const ENEMY_AIRCRAFT_CAREER_BULLET_MAX_COUNT = 10;

export const ENEMY_AIRCRAFT_CAREER_GROUP_SPAWN_START = 4000;
export const ENEMY_AIRCRAFT_CAREER_GROUP_SPAWN_INTERVAL = 35000;


export const ENEMY_DESTROYER_HEALTH = 10;
export const ENEMY_DESTROYER_SCORE = 300;
export const ENEMY_DESTROYER_MOVEMENT_VERTICAL_VELOCITY = 1;
export const ENEMY_DESTROYER_BULLET_SPEED = -150; //needs to be negative to go down or you can multiply by flipY
export const ENEMY_DESTROYER_BULLET_INTERVAL = 2000;
export const ENEMY_DESTROYER_BULLET_LIFESPAN = 8;
export const ENEMY_DESTROYER_BULLET_MAX_COUNT = 10;

export const ENEMY_DESTROYER_GROUP_SPAWN_START = 4000;
export const ENEMY_DESTROYER_GROUP_SPAWN_INTERVAL = 35000;



export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;

export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;


